-- نظام إشعارات مكتبتي + سجل دخول التلاميذ
create table if not exists public.notifications (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    message text not null,
    type text not null default 'general',
    target_type text not null default 'all' check (target_type in ('all','class','user')),
    target_user_id uuid null references auth.users(id) on delete cascade,
    target_branch text null,
    target_year integer null,
    target_subject text null,
    link text null,
    created_by uuid null references auth.users(id) on delete set null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists notifications_target_idx
on public.notifications (target_type, target_branch, target_year, created_at desc);

create index if not exists notifications_user_idx
on public.notifications (target_user_id, created_at desc);

create table if not exists public.notification_reads (
    notification_id uuid not null references public.notifications(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    read_at timestamptz not null default now(),
    primary key (notification_id, user_id)
);

create table if not exists public.login_activity (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null,
    branch text null,
    year integer null,
    logged_in_at timestamptz not null default now()
);

create index if not exists login_activity_month_idx
on public.login_activity (role, logged_in_at desc);

create index if not exists login_activity_user_idx
on public.login_activity (user_id, logged_in_at desc);

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.login_activity enable row level security;

-- الخادم يستخدم Service Role Key، لذلك لا نحتاج سياسات عامة للعمليات الحساسة.


-- إضافات اختيارية للنظام: المشاهدات والواجبات وإشعارات FCM
create table if not exists public.platform_file_views (
    file_id uuid not null references public.platform_files(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    viewed_at timestamptz not null default now(),
    primary key (file_id, user_id)
);
create index if not exists platform_file_views_file_idx on public.platform_file_views(file_id, viewed_at desc);
create index if not exists platform_file_views_user_idx on public.platform_file_views(user_id, viewed_at desc);

create table if not exists public.homework_submissions (
    id uuid primary key default gen_random_uuid(),
    note_id uuid not null references public.platform_notes(id) on delete cascade,
    student_id uuid not null references auth.users(id) on delete cascade,
    drive_file_id text not null,
    file_name text,
    file_url text,
    submitted_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(note_id, student_id)
);
create index if not exists homework_submissions_note_idx on public.homework_submissions(note_id, submitted_at desc);
create index if not exists homework_submissions_student_idx on public.homework_submissions(student_id, submitted_at desc);

create table if not exists public.push_device_tokens (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    token text not null unique,
    platform text not null default 'android',
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);
create index if not exists push_device_tokens_user_idx on public.push_device_tokens(user_id);

alter table public.platform_notes add column if not exists homework_file_drive_id text;
alter table public.platform_notes add column if not exists homework_file_url text;
alter table public.platform_notes add column if not exists homework_file_name text;
alter table public.platform_notes add column if not exists submission_deadline timestamptz;

alter table public.platform_file_views enable row level security;
alter table public.homework_submissions enable row level security;
alter table public.push_device_tokens enable row level security;

create table if not exists public.platform_note_views (
    note_id uuid not null references public.platform_notes(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    viewed_at timestamptz not null default now(),
    primary key (note_id, user_id)
);
create index if not exists platform_note_views_note_idx on public.platform_note_views(note_id, viewed_at desc);
alter table public.platform_note_views enable row level security;
