-- نظام إشعارات مكتبتي + سجل دخول التلاميذ
create table if not exists public.notifications (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    message text not null,
    type text not null default 'general',
    target_type text not null default 'all' check (target_type in ('all','class','user')),
    target_user_id uuid null references auth.users(id) on delete cascade,
    target_branch text null,
    target_year integer null,
    target_subject text null,
    link text null,
    created_by uuid null references auth.users(id) on delete set null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create index if not exists notifications_target_idx
on public.notifications (target_type, target_branch, target_year, created_at desc);

create index if not exists notifications_user_idx
on public.notifications (target_user_id, created_at desc);

create table if not exists public.notification_reads (
    notification_id uuid not null references public.notifications(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    read_at timestamptz not null default now(),
    primary key (notification_id, user_id)
);

create table if not exists public.login_activity (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null,
    branch text null,
    year integer null,
    logged_in_at timestamptz not null default now()
);

create index if not exists login_activity_month_idx
on public.login_activity (role, logged_in_at desc);

create index if not exists login_activity_user_idx
on public.login_activity (user_id, logged_in_at desc);

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;
alter table public.login_activity enable row level security;

-- الخادم يستخدم Service Role Key، لذلك لا نحتاج سياسات عامة للعمليات الحساسة.
